/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "pwm.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void gpio_intialization(){
	RCC_AHB1ENR |=(1<<2);
	GPIOC_MODER &=~(3<<12);  //clearing the MODER
	GPIOC_MODER |=(2<<12);   //setting the MODER to Alternate function mode
	GPIOC_AFRL &=~(0xF<<24);   //clearing the Alternate function (24,25,26,27) bits
	GPIOC_AFRL |=(0x2<<24);    //we are using AF2 so set the value to 2 (0010)
}

void timer3_intialization(){
	RCC_APB1ENR |=(1<<1);     //enable the TIM3 Clock using RCC
	TIM3_PSC=0;               //PSC dividing factor is '0'
//	TIM3_ARR=16000-1;         //Counter max value is 16KHz through ARR
	TIM3_CNT=0;               //intialise counter to '0'
	TIM3_CCMR1 &=~(7<<4);     //clear the CCMR in bit 4,5,6       Page no.678
	TIM3_CCMR1 |=(6<<4);      //setting to 110-PWM mode in bit 4,5,6
	TIM3_CCMR1 |=(1<<3);      //enabling CCR preload in 3rd bit
	TIM3_CCER  |=(1<<1);      //enabling the Active LOW polarity enable   576
	TIM3_CCER  |=(1<<0);      //send timer output to PC6                  576
	TIM3_EGR   |=(1<<0);      //update all registers                      635
	TIM3_CR1   |=(1<<0);      //Enable the counter in '0' bit             672
	TIM3_CR1   |=(1<<7);      //Auto preload enable the counter           672
}

void tim3_pc6_set_dutycycle(uint32_t freq, uint32_t duty_cycle, uint8_t channel){
	TIM3_ARR=(16000000/freq-1);
	switch(channel){
	case 1:
		TIM3_CCR1=(uint32_t)((TIM3_ARR * duty_cycle)/100);
		break;
	default:
		break;
	}
}

int main(void)
{
	gpio_intialization();
	timer3_intialization();

	while(1){
		tim3_pc6_set_dutycycle(1000,10,1);
		for(int i=0;i<300000;i++);
		tim3_pc6_set_dutycycle(1000,50,1);
		for(int i=0;i<300000;i++);
		tim3_pc6_set_dutycycle(1000,100,1);
		for(int i=0;i<300000;i++);
	}

    /* Loop forever */
	for(;;);
}
